apiVersion: v1
kind: ConfigMap
metadata:
  name: news-service-dev
  labels:
    app: news-service-dev
data:
  ENVIRONMENT: dev
  APP_NAME: news-service
  DATABASE_URL: ${DATABASE_URL_DEV}
  AUTH_SECRET_KEY: ${AUTH_SECRET_KEY}
  MINIO_IMAGE_STORAGE: ${MINIO_IMAGE_STORAGE}
  MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
