apiVersion: v1
kind: ConfigMap
metadata:
  name: news-service
  labels:
    app: news-service
data:
  ENVIRONMENT: prod
  APP_NAME: news-service
  APP_COLOR: green
  ASSETS_DIR: /app/assets
  SALT: ${SALT}
  JWT_ACCESS_TOKEN_SECRET: ${JWT_ACCESS_TOKEN_SECRET}
  JWT_ACCESS_TOKEN_EXPIRATION_TIME: ${JWT_ACCESS_TOKEN_EXPIRATION_TIME}
  JWT_REFRESH_TOKEN_SECRET: ${JWT_REFRESH_TOKEN_SECRET}
  JWT_REFRESH_TOKEN_EXPIRATION_TIME: ${JWT_REFRESH_TOKEN_EXPIRATION_TIME}
  DATABASE_URL: ${DATABASE_URL_PROD}
